name: webilastik
channels:
  - ilastik-forge
  - conda-forge
dependencies:
  - python>=3.8
  - numpy=1.24.2
  - fastfilters
  - lemon
  - vigra=1.11.1
  - imath=3.1.6
  - scikit-image
  - scikit-learn
  - scipy=1.9.1
  - h5py=3.7
  - typing_extensions
  - aiohttp
  - requests
  - redis
  - redis-py=4.4.2
  - cryptography
  - defusedxml
  - pip
  - pip:
    - numpy==1.24.2
    - git+https://git@github.com/ilastik/ndstructs@43b27382e964211a5e4d94148f826ec83d514636
    - dask-mpi==2022.4.0
    - mpi4py==3.1.4
