name: webilastik
channels:
  - ilastik-forge
  - conda-forge
dependencies:
  - python>=3.8
  - numpy
  - fastfilters
  - lemon
  - vigra
  - scikit-image
  - scikit-learn
  - h5py
  - typing_extensions
  - aiohttp
  - requests
  - redis
  - redis-py
  - cryptography
  - defusedxml
  - pip
  - pip:
    - git+https://git@github.com/ilastik/ndstructs@1a5b02d34df0517ef6f3d1ba863e2e8169daf76a
